#!/usr/bin/env bash
# =============================================================================
# CMS Setup Script
# =============================================================================
# Prepares the CMS deployment environment:
#   1. Generates secrets (JWT, subsystem, DB password, MinIO credentials)
#   2. Writes .env
#   3. Generates a self-signed TLS certificate
#   4. Writes an Nginx reverse-proxy config
#
# At the end, prints the values the AIS developer needs to put in their .env.
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
#
# Run once on the CMS machine before starting the application.
# Safe to re-run: existing .env and certificates are not overwritten.
#
# Prerequisites: openssl
# =============================================================================

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }
header()  { echo -e "\n${BOLD}$*${RESET}"; }

# ── Dependency check ──────────────────────────────────────────────────────────
command -v openssl >/dev/null 2>&1 || error "openssl is required but not installed."

# =============================================================================
# 1. Generate secrets
# =============================================================================
header "── Step 1: Generating secrets ──────────────────────────────────────────"

JWT_SECRET=$(openssl rand -base64 32)
SUBSYSTEM_SECRET=$(openssl rand -base64 24)
DB_PASSWORD=$(openssl rand -base64 18 | tr -dc 'a-zA-Z0-9' | head -c 24)
MINIO_ACCESS_KEY=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | head -c 16)
MINIO_SECRET_KEY=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)

success "Secrets generated."

# =============================================================================
# 2. Write .env
# =============================================================================
header "── Step 2: Writing .env ────────────────────────────────────────────────"

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    warn ".env already exists — skipping. Delete it and re-run to regenerate."
else
    # Prompt for optional values
    read -rp "  CMS hostname or IP (e.g. cms.example.com or 192.168.1.10): " CMS_HOST
    CMS_HOST=${CMS_HOST:-localhost}

    read -rp "  MinIO machine IP or hostname (e.g. 192.168.1.20):          " MINIO_HOST
    MINIO_HOST=${MINIO_HOST:-localhost}

    cat > "$ENV_FILE" <<EOF
# ============================================================
# CMS Environment — generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do NOT commit this file to version control.
# ============================================================

# ── PostgreSQL ──
DB_NAME=cms_db
DB_URL=jdbc:postgresql://localhost:5432/cms_db
DB_USERNAME=cms_user
DB_PASSWORD=${DB_PASSWORD}
DB_PORT=5432

# ── MinIO ──
MINIO_ENDPOINT=http://${MINIO_HOST}:9000
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
MINIO_BUCKET=anomaly-clips
MINIO_API_PORT=9000
MINIO_CONSOLE_PORT=9001

# ── JWT ──
JWT_SECRET=${JWT_SECRET}

# ── Subsystem (AI Inference Node) ──
SUBSYSTEM_ID=ai-inference-node
SUBSYSTEM_SECRET=${SUBSYSTEM_SECRET}

# ── CMS public address (used in Nginx config) ──
CMS_HOST=${CMS_HOST}
EOF

    success ".env written."
fi

# Re-read values from .env for use in later steps
# shellcheck source=.env
set -o allexport
# shellcheck disable=SC1091
source "$ENV_FILE"
set +o allexport

# =============================================================================
# 3. Self-signed TLS certificate
# =============================================================================
header "── Step 3: TLS certificate ─────────────────────────────────────────────"

CERT_DIR="./nginx/certs"
CERT_FILE="$CERT_DIR/cms.crt"
KEY_FILE="$CERT_DIR/cms.key"

mkdir -p "$CERT_DIR"

if [ -f "$CERT_FILE" ] && [ -f "$KEY_FILE" ]; then
    warn "Certificate already exists at $CERT_FILE — skipping."
else
    CMS_HOST=${CMS_HOST:-localhost}
    info "Generating self-signed certificate for: $CMS_HOST"

    openssl req -x509 -newkey rsa:4096 -sha256 -days 365 \
        -nodes \
        -keyout "$KEY_FILE" \
        -out "$CERT_FILE" \
        -subj "/CN=${CMS_HOST}/O=CMS/C=TR" \
        -addext "subjectAltName=DNS:${CMS_HOST},IP:127.0.0.1" \
        2>/dev/null

    chmod 600 "$KEY_FILE"
    success "Certificate written to $CERT_FILE"
    info  "  Key written to $KEY_FILE"
    warn  "  This is a SELF-SIGNED certificate."
    warn  "  AIS must either trust this cert explicitly or disable cert verification."
    warn  "  For production, replace with a CA-signed certificate (e.g. Let's Encrypt)."
fi

# =============================================================================
# 4. Nginx config
# =============================================================================
header "── Step 4: Nginx config ─────────────────────────────────────────────────"

NGINX_CONF_DIR="./nginx"
NGINX_CONF="$NGINX_CONF_DIR/cms.conf"

mkdir -p "$NGINX_CONF_DIR"

if [ -f "$NGINX_CONF" ]; then
    warn "Nginx config already exists at $NGINX_CONF — skipping."
else
    CMS_HOST=${CMS_HOST:-localhost}

    cat > "$NGINX_CONF" <<NGINX
# ============================================================
# Nginx reverse-proxy config for CMS
# Generated by setup.sh
#
# Install:
#   sudo cp nginx/cms.conf /etc/nginx/sites-available/cms
#   sudo ln -s /etc/nginx/sites-available/cms /etc/nginx/sites-enabled/
#   sudo cp nginx/certs/cms.crt /etc/ssl/certs/cms.crt
#   sudo cp nginx/certs/cms.key /etc/ssl/private/cms.key
#   sudo nginx -t && sudo systemctl reload nginx
# ============================================================

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name ${CMS_HOST};
    return 301 https://\$host\$request_uri;
}

# HTTPS
server {
    listen 443 ssl http2;
    server_name ${CMS_HOST};

    ssl_certificate     /etc/ssl/certs/cms.crt;
    ssl_certificate_key /etc/ssl/private/cms.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    # REST API
    location /api/ {
        proxy_pass         http://127.0.0.1:8050;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 30s;
    }

    # WebSocket (AIS config sync + camera status)
    # Upgrade headers are required — without them the WS handshake fails.
    location /ws/ {
        proxy_pass             http://127.0.0.1:8050;
        proxy_http_version     1.1;
        proxy_set_header       Upgrade \$http_upgrade;
        proxy_set_header       Connection "upgrade";
        proxy_set_header       Host \$host;
        proxy_set_header       X-Real-IP \$remote_addr;
        proxy_read_timeout     3600s;
        proxy_send_timeout     3600s;
    }
}
NGINX

    success "Nginx config written to $NGINX_CONF"
fi

# =============================================================================
# 5. Summary
# =============================================================================
header "── Setup complete ───────────────────────────────────────────────────────"

echo ""
echo -e "${BOLD}Generated files:${RESET}"
echo "  .env                  — environment variables for CMS and Docker Compose"
echo "  nginx/cms.conf        — Nginx reverse-proxy config (copy to /etc/nginx/...)"
echo "  nginx/certs/cms.crt   — TLS certificate"
echo "  nginx/certs/cms.key   — TLS private key (keep on this machine only)"
echo ""
echo -e "${BOLD}Next steps:${RESET}"
echo "  1. Start infrastructure:"
echo "       docker compose up -d"
echo ""
echo "  2. Build and run CMS:"
echo "       ./mvnw clean package -DskipTests"
echo "       java -jar target/cms-*.jar"
echo ""
echo "  3. Install Nginx config:"
echo "       sudo cp nginx/cms.conf /etc/nginx/sites-available/cms"
echo "       sudo ln -s /etc/nginx/sites-available/cms /etc/nginx/sites-enabled/"
echo "       sudo cp nginx/certs/cms.crt /etc/ssl/certs/cms.crt"
echo "       sudo cp nginx/certs/cms.key /etc/ssl/private/cms.key"
echo "       sudo nginx -t && sudo systemctl reload nginx"
echo ""
echo "  4. Verify CMS is up:"
echo "       curl -k https://${CMS_HOST:-localhost}/actuator/health"
echo ""
echo -e "${BOLD}${YELLOW}── Give the following to the AIS developer ─────────────────────────────${RESET}"
echo ""
echo "  Copy these into the AIS .env file:"
echo ""
echo "    CMS_URL=https://${CMS_HOST:-<cms-host>}"
echo "    CMS_WS_URL=wss://${CMS_HOST:-<cms-host>}/ws/inference-sync"
echo "    CMS_SUBSYSTEM_ID=${SUBSYSTEM_ID:-ai-inference-node}"
echo "    CMS_SUBSYSTEM_SECRET=${SUBSYSTEM_SECRET:-<see .env>}"
echo ""
if [ -f "$CERT_FILE" ]; then
echo "  Also copy the TLS certificate to the AIS machine so it can trust CMS:"
echo ""
echo "    nginx/certs/cms.crt"
echo ""
echo "  Then on the AIS machine, configure its HTTP client to trust this cert"
echo "  (or add it to the system trust store)."
fi
echo ""
warn "Keep .env and nginx/certs/cms.key out of version control — they are in .gitignore."
echo ""





