package com.bitiriciler32.cms.analytics.entity;

import com.bitiriciler32.cms.management.entity.CameraEntity;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

/**
 * Pre-computed daily model performance summary for analytics dashboards.
 * Generated by DailySummaryScheduler.
 */
@Entity
@Table(name = "daily_model_summaries")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DailyModelSummaryEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private LocalDate date;

    private String modelVersion;

    @Column(nullable = false)
    private Long totalEvents;

    @Column(nullable = false)
    private Long falsePositiveCount;

    @Column(nullable = false)
    private Double falsePositiveRate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "camera_id")
    private CameraEntity camera;
}
